apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: canary1
  name: canary1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: canary1
    spec:
      containers:
      - image: imran90306/loginpage:v2
        name: vprofile
        resources: {}
status: {}
