apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo1
  name: argo1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo1
    spec:
      containers:
      - image: imran90306/javacal:w1
        name: javacal
        resources: {}
status: {}
